{
 "title": "Weather Forecast",
 "time": { "from": "2025-05-06T18:19:52.296Z", "to": "2025-05-09T18:52:50.922Z" },
 "templating": {
  "list": [
   {
    "name": "fc_time",
    "label": "Forecast time",
    "query": "SELECT DISTINCT TO_CHAR(fc_time, 'YYYY-MM-DD HH24:MI:SSOF') FROM public.forecasts"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Horizontal Irradiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT obs_time AS \"time\", value AS \"global horizontal irradiation\" FROM public.forecasts WHERE dp_id = (SELECT id FROM data_points WHERE name = 'global_horizontal_irradiation' AND data_provider = 'ZAMG.NWP') AND FLOOR(EXTRACT(EPOCH FROM fc_time)) = EXTRACT(EPOCH FROM TIMESTAMP '$fc_time')"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "rawSql": "SELECT obs_time AS \"time\", value AS \"wind speed\" FROM public.forecasts WHERE dp_id = (SELECT id FROM data_points WHERE name = 'wind_speed_10m' AND data_provider = 'ZAMG.NWP') AND FLOOR(EXTRACT(EPOCH FROM fc_time)) = EXTRACT(EPOCH FROM TIMESTAMP '$fc_time')"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT obs_time AS \"time\", value AS \"air temperature\" FROM public.forecasts WHERE dp_id = (SELECT id FROM data_points WHERE name = 'air_temperature_2m' AND data_provider = 'ZAMG.NWP') AND FLOOR(EXTRACT(EPOCH FROM fc_time)) = EXTRACT(EPOCH FROM TIMESTAMP '$fc_time')"
    }
   ]
  },
  {
   "title": "Cloud Area Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT obs_time AS \"time\", value AS \"cloud area fraction\" FROM public.forecasts WHERE dp_id = (SELECT id FROM data_points WHERE name = 'cloud_area_fraction' AND data_provider = 'ZAMG.NWP') AND FLOOR(EXTRACT(EPOCH FROM fc_time)) = EXTRACT(EPOCH FROM TIMESTAMP '$fc_time')"
    }
   ]
  }
 ]
}