services:

  ## -----------------------------------------------------------------
  ## Use Redis streams for data access of micro-services in real-time.
  ## -----------------------------------------------------------------
  redis:
    image: "redis:7.2.4-alpine"
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: unless-stopped
    ## Expose ports only for debugging.
    # ports:
    #  - "6379:6379"

  ## ---------------------------------------------------------------------------------
  ## For debugging: use Redis Insight browser to explore the content of redis streams.
  ## ---------------------------------------------------------------------------------
  redis-insight:
    image: redis/redisinsight
    restart: unless-stopped
    environment:
      - RI_REDIS_HOST0=redis
      - RI_REDIS_PORT0=6379
      - RI_REDIS_PASSWORD0=${REDIS_PASSWORD}
      - RI_REDIS_ALIAS0=Tutorial Redis Database
    ports:
      - 5540:5540
    depends_on:
      - redis

volumes:
  redis-data:
