services:

  ## -----------------------------------------------------------------
  ## Use Redis streams for data access of micro-services in real-time.
  ## -----------------------------------------------------------------
  redis:
    image: "redis:7.2.4-alpine"
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: unless-stopped
    ## Expose ports only for debugging.
    # ports:
    #  - "6379:6379"

  ## -----------------------------------------------
  ## This micro-service retrieves weather forecasts.
  ## -----------------------------------------------
  weather-data-service:
    image: ait1/rdp-data-crawler:latest-dev
    volumes:
      - ./weather-data-service/config.yml:/etc/data_crawler/config.yml:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: unless-stopped

  ## ----------------------------------------------------------
  ## Use TimescaleDB for permanent storage of time series data.
  ## ----------------------------------------------------------
  timescale:
    image: "timescale/timescaledb:latest-pg16"
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: unless-stopped
    ## Expose ports only for debugging.
    # ports:
    #  - "5432:5432"

  ## ------------------------------------------------------------------------
  ## This micro-service defines the database schema used by the timescale DB.
  ## ------------------------------------------------------------------------
  db-scheme:
    image: ait1/rdp-database:latest-dev
    depends_on:
      - timescale
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DATA_SOURCE_USER: ${POSTGRES_DATA_SOURCE_USER}
      POSTGRES_DATA_SOURCE_PASSWORD: ${POSTGRES_DATA_SOURCE_PASSWORD}
      POSTGRES_DATA_VIS_USER: ${POSTGRES_DATA_VIS_USER}
      POSTGRES_DATA_VIS_PASSWORD: ${POSTGRES_DATA_VIS_PASSWORD}
      POSTGRES_DATA_PUB_VIS_USER: ${POSTGRES_DATA_PUB_VIS_USER}
      POSTGRES_DATA_PUB_VIS_PASSWORD: ${POSTGRES_DATA_PUB_VIS_PASSWORD}
      RDP_POSTGRES_HOST: timescale

  ## ----------------------------------------------------------------------------------
  ## This micro-service stores selected data from the Redis stream to the TtimescaleDB.
  ## ----------------------------------------------------------------------------------
  data-sync-service:
    image: ait1/rdp-redsql:latest-dev
    environment:
      POSTGRES_USER: ${POSTGRES_DATA_SOURCE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATA_SOURCE_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./data-sync-service/config.yml:/etc/redsql/config.yml:ro
    depends_on:
      redis:
        condition: service_started
      db-scheme:
        condition: service_completed_successfully
    restart: unless-stopped

  ## ----------------------------------------------------------
  ## Use grafana for visualization of data in the timescale DB.
  ## ----------------------------------------------------------
  grafana:
    image: grafana/grafana-oss:10.2.3
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      POSTGRES_DATA_VIS_USER: ${POSTGRES_DATA_VIS_USER}
      POSTGRES_DATA_VIS_PASSWORD: ${POSTGRES_DATA_VIS_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    depends_on:
      db-scheme:
        condition: service_completed_successfully
    restart: unless-stopped

  ## ------------------------------------------------------------------------------------
  ## This micro-service uses the latest forecast data for running a PV module simulation.
  ## ------------------------------------------------------------------------------------
  pv-sim-service:
    build: pv-sim-service
    volumes:
      - ./pv-sim-service/config.yml:/app/config.yml:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - weather-data-service
    restart: unless-stopped

  ## ---------------------------------------------------------------------------------
  ## For debugging: use Redis Insight browser to explore the content of redis streams.
  ## ---------------------------------------------------------------------------------
  redis-insight:
    image: redis/redisinsight
    restart: unless-stopped
    environment:
      - RI_REDIS_HOST0=redis
      - RI_REDIS_PORT0=6379
      - RI_REDIS_PASSWORD0=${REDIS_PASSWORD}
      - RI_REDIS_ALIAS0=Tutorial Redis Database
    ports:
      - 5540:5540
    depends_on:
      - redis

volumes:
  redis-data:
  timescale-data:
  grafana-data:
