version: 1

pv_sim:
  input_stream: "geosphere.forecasts.nwp.WIEN-HOHE_WARTE"
  output_stream: "pvsim.forecasts.WIEN-HOHE_WARTE"
  location: "WIEN-HOHE_WARTE"

redis:
  host: "redis"
  port: 6379
  db: 0
  password: ${REDIS_PASSWORD}

logging:
  loggers:
    pv_sim:
      level: "INFO"
      handlers: ["console"]
